### ISSUE TITLE
Add a build system that meets modern expectations.

### ISSUE THREAD

**Issue by mikehaertel** [mikehaertel/minrx#10]
Top candidates are probably autoconf+gmake or meson.

**Comment by arnoldrobbins** [comment]
Please bear in mind that MinRX needs to be "drop in-able" into other peoples' code... I am willing to help if you want to go the autoconf + make route, as that's what gawk uses.

**Comment by mikehaertel** [comment]
Closing this issue thanks to shenleban tongying's contribution of a meson build.
